# Generated by Django 4.0.4 on 2023-11-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('file_path', models.FileField(upload_to='documents/')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('some_info', models.TextField(blank=True, default='No information', verbose_name='f')),
                ('author', models.CharField(default='No information', max_length=70, verbose_name='Автор')),
                ('time_publish', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(default='cover/image.png', upload_to='cover')),
            ],
        ),
    ]
