# Generated by Django 4.2.7 on 2023-11-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=70, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='document',
            name='some_info',
            field=models.TextField(blank=True, verbose_name='f'),
        ),
    ]
