# Generated by Django 4.2.7 on 2023-11-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0002_alter_document_author_alter_document_some_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
