# Generated by Django 4.2.7 on 2023-11-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0003_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='essay',
            field=models.TextField(blank=True, verbose_name='Essay'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
