# Generated by Django 4.2.7 on 2023-11-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0005_rename_some_info_document_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='Keywords'),
        ),
    ]
