# Generated by Django 4.2.7 on 2023-11-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0007_alter_document_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Keywords'),
        ),
    ]
